/* global Object */

/**
 * Exact audited base schema plus the additive, owner-approval-gated payout
 * schema. Do not relax these arrays to make a drifting workbook pass.
 */
var HFLA_PAYOUT_SCHEMA = Object.freeze({
  version: "artist-payout-schema-v1",
  sheetIds: Object.freeze({
    "02_BOOKINGS": 2,
    "03_PAYMENT_TRACKER": 3,
    "10_AUDIT_LOG": 10,
    "11_ARTIST_PAYMENTS": 11011,
    "12_ARTIST_ROSTER": 12012,
    "13_ARTIST_ASSIGNMENTS": 13013,
  }),
  base: Object.freeze({
    "02_BOOKINGS": Object.freeze([
      "Booking ID",
      "Linked Lead ID",
      "Booking Created Date",
      "Client Name",
      "Client Phone",
      "Client Email",
      "Event Date",
      "Start Time",
      "End Time",
      "Event Address",
      "Event City",
      "Service / Package",
      "Estimated Kids / Guests",
      "Party Theme",
      "Event Total",
      "Booking Retainer Amount",
      "Booking Retainer Paid Date",
      "Remaining Balance",
      "Travel Fee",
      "Tax Review Status",
      "Payment Status",
      "Booking Status",
      "Table + Chairs Confirmed?",
      "Parking / Access Confirmed?",
      "Indoor / Outdoor",
      "Artist Assigned",
      "Official Confirmation Sent?",
      "Day-Before Reminder Sent?",
      "Event Completed?",
      "Review Requested?",
      "Internal Notes",
      "Nontaxable Service Subtotal",
      "Taxable Balloon / Product Subtotal",
      "Sales Tax Rate",
      "Sales Tax Amount",
      "Tax Rate Checked Date",
      "Tax Rate Source / Notes",
      "Seller Permit Required?",
      "Seller Permit Confirmed?",
      "All Details Confirmed?",
      "Confirmation Readiness",
      "Parking / Access Details",
    ]),
    "03_PAYMENT_TRACKER": Object.freeze([
      "Payment ID",
      "Booking ID",
      "Client Name",
      "Event Date",
      "Event Total",
      "Booking Retainer Due",
      "Booking Retainer Paid",
      "Retainer Payment Date",
      "Remaining Balance",
      "Balance Paid",
      "Balance Payment Date",
      "Nontaxable Service Subtotal",
      "Taxable Balloon / Product Subtotal",
      "Sales Tax Rate",
      "Sales Tax Amount",
      "Optional Tip",
      "Refund Amount",
      "Refund Date",
      "Payment Method",
      "Payment Link Sent?",
      "Retainer Receipt Sent?",
      "Final Receipt Sent?",
      "Tax Review Status",
      "Payment Status",
      "Notes",
    ]),
    "10_AUDIT_LOG": Object.freeze([
      "Timestamp",
      "Changed By",
      "Area Changed",
      "Change Type",
      "Old Value",
      "New Value",
      "Reason",
      "Approval Source",
      "Notes",
    ]),
    "11_ARTIST_PAYMENTS": Object.freeze([
      "Artist Payment ID",
      "Booking ID",
      "Lead ID",
      "Event Date",
      "Event Time",
      "Client Name",
      "Event City",
      "Artist Name",
      "Artist Phone",
      "Artist Email",
      "Payment Method",
      "Payment Handle",
      "Service Pay",
      "Travel Pay",
      "Tip / Bonus",
      "Total Artist Pay",
      "Completion Confirmed?",
      "Approved By",
      "Payment Status",
      "Paid Date",
      "Payment Memo Used",
      "Receipt Screenshot Link",
      "W-9 on File?",
      "1099 Trackable?",
      "Reconciled?",
      "Notes",
      "Created At",
      "Last Updated",
      "Artist ID",
      "Assignment ID",
    ]),
    "12_ARTIST_ROSTER": Object.freeze([
      "Artist ID",
      "Artist Status",
      "Legal Full Name",
      "Preferred Name",
      "Artist Type",
      "Primary Service Role",
      "Services Offered",
      "Skill / Event Level",
      "Home Base City",
      "Service Regions",
      "Max Travel / Notes",
      "Phone",
      "Email",
      "Payment Method",
      "Payment Handle",
      "Standard Pay Notes",
      "Travel Pay Rule",
      "Own Supplies?",
      "Own Table / Chair?",
      "Insurance Status",
      "W-9 Status",
      "Agreement Status",
      "Portfolio / Social Link",
      "Secure Docs Folder Link",
      "Reliability Notes",
      "Dispatch Notes",
      "Created At",
      "Last Updated",
      "Vehicle / Plate Info",
      "Website / Portfolio URL",
    ]),
    "13_ARTIST_ASSIGNMENTS": Object.freeze([
      "Assignment ID",
      "Booking ID",
      "Lead ID",
      "Event Date",
      "Start Time",
      "End Time",
      "Client / Event Name",
      "Event City",
      "Event Address",
      "Service Role",
      "Artist ID",
      "Artist Name",
      "Artist Phone",
      "Artist Email",
      "Assignment Status",
      "Artist Confirmed?",
      "Dispatch Sent?",
      "On Way Confirmed?",
      "Arrived Confirmed?",
      "Setup Ready Confirmed?",
      "Completed Confirmed?",
      "Actual End Time",
      "Extra Time / Issue Flag",
      "Agreed Service Pay",
      "Agreed Travel Pay",
      "Total Agreed Pay",
      "Payment Record ID",
      "Closeout Notes",
      "Created At",
      "Last Updated",
    ]),
  }),
  extensions: Object.freeze({
    "11_ARTIST_PAYMENTS": Object.freeze([
      "Payout Environment",
      "Payout Ledger ID",
      "Payout Source Revision",
      "Payout State",
      "Payout Batch ID",
      "Payout Batch Date",
      "Payout Currency",
      "Total Approved Pay Cents",
      "Stripe Connected Account ID",
      "Stripe Transfer ID",
      "Stripe Payout ID",
      "Stripe Payout Status",
      "Payout Reconciled?",
      "Payout Reconciled At",
      "Manual Payment Method",
      "Manual Payment Reason",
      "Manual Payment Evidence Reference",
      "Manual Payment Memo",
      "Manual Payment Recorded By",
      "Manual Payment Recorded At",
      "Payout Last Verified At",
      "Payout Projection Revision",
      "Pay Adjustment",
      "Pay Deduction",
    ]),
    "12_ARTIST_ROSTER": Object.freeze([
      "Stripe Country",
      "Stripe Legal Entity Type",
      "Stripe Connected Account ID",
      "Stripe Onboarding Status",
      "Stripe Requirements Status",
      "Stripe Transfers Enabled",
      "Stripe Payout Ready",
      "Stripe Dashboard Type",
      "Preferred Payout Type",
      "Last Stripe Requirements Check",
      "Stripe Onboarded Date",
      "Stripe Disabled Reason",
      "Payout Exception Flag",
    ]),
    "13_ARTIST_ASSIGNMENTS": Object.freeze([
      "Assignment Source Revision",
      "Closeout Verified At",
      "Artist Completion Confirmed?",
      "Extra Time Reconciled?",
      "Service Change Reconciled?",
      "Travel Pay Reconciled?",
      "Adjustments Reconciled?",
      "No Customer Complaint Affecting Pay?",
      "No Refund Issue Affecting Pay?",
      "No Damage Or Supply Issue Affecting Pay?",
      "Compensation Approved?",
      "Contractor Control Satisfied?",
      "Closeout Status",
      "Assignment Policy Version",
    ]),
  }),
});

function expectedHeaders_(sheetName, migrated) {
  var base = HFLA_PAYOUT_SCHEMA.base[sheetName];
  if (!base) throw new Error("Unapproved Booking Control Center tab");
  var extension = HFLA_PAYOUT_SCHEMA.extensions[sheetName] || [];
  return migrated ? base.concat(extension) : base.slice();
}

function exactStringArray_(actual, expected) {
  if (!Array.isArray(actual) || actual.length !== expected.length) return false;
  for (var i = 0; i < expected.length; i += 1) {
    if (actual[i] !== expected[i]) return false;
  }
  return true;
}

function headerIndex_(headers) {
  var index = Object.create(null);
  for (var i = 0; i < headers.length; i += 1) {
    if (typeof headers[i] !== "string" || !headers[i]) {
      throw new Error("Booking Control Center contains a blank header");
    }
    if (Object.prototype.hasOwnProperty.call(index, headers[i])) {
      throw new Error("Booking Control Center contains a duplicate header");
    }
    index[headers[i]] = i;
  }
  return index;
}
